### ISSUE TITLE
V4.0.0 Release

### ISSUE THREAD

**Issue by raymondboswel** [timdeschryver/ngrx-etc#12]
Hi Tim! 

Will you please release 4.0.0 on NPM? I've upgraded to angular 9 / ngrx 9, and for some reason pointing my package.json directly to github to get the latest code doesn't work.

Thanks for this lib, it really improves the ergonomics of writing reducers.

**Comment by timdeschryver** [comment]
Hey!

Thanks for raising this issue, I thought it was published but sadly something went wrong.
I will take a look later today.

**Comment by timdeschryver** [comment]
Should be available now @raymondboswel , if you experience any problems feel free to create an issue for it :)
