### ISSUE TITLE
ngrx-etc not working in IE11.

### ISSUE THREAD

**Issue by atrifyllis** [timdeschryver/ngrx-etc#15]
Has this been tested in IE11 (es5 mode)?. Immer 6 has changed the way it supports es5:
https://immerjs.github.io/immer/docs/installation

It seems that the es5 plugin need to be enabled somehow but calling enableES5 method from inside my app does not seem to work. I also found this comment:

https://github.com/immerjs/immer/issues/601#issuecomment-632162664

Is it possible that es5 support must be enabled from inside ngrx-etc?

**Comment by christianlundberg** [comment]
Yep, same thing happened to me. It won't work on IE. Even tried adding immer as a dependency to my own package.json, but that didn't work either. The problem is that ngrx-etc is listing immer as a dependency, instead it should be a peer dependency so that we can install immer ourselves and call enableES5 if we need to.

**Comment by timdeschryver** [comment]
I haven't taken a look yet, but does Immer v7 resolves this issue?
I'm planning to update it very soon, I'm also open to PRs so if someone wants to grab that one, feel free 🙂

@christianlundberg The reason why it's listed as a dependency is that I don't want that users have to install immer.  I see it as an implementation detail, that can be changed in future versions. Does that make sense?

**Comment by christianlundberg** [comment]
I ran `npm ls immer` and ngrx-etc is the only package that uses immer in my case, so I'm not really sure why calling enableES5 doesn't work. I guess you'd have to call it somewhere within the package.

**Comment by atrifyllis** [comment]
In the comment I linked it states "It might be that enableES5 needs to be called by one of the dependencies
that you are trying to use, if they are bundling their own version" (of immer). So the plugins must be enabled from inside ngrx-etc but should they always be enabled or maybe provide an option in ngrx-etc to enable them on demand?

**Comment by christianlundberg** [comment]
Definitely not always enabled. Should probably just create wrapper functions that simply call the immer functions.

**Comment by timdeschryver** [comment]
👍 do you want to create a PR that adds this?

**Comment by timdeschryver** [comment]
Hi, I just released v5.
This version re-exports the `enableES5`, `enableMapSet`, `enablePatches`, and `enableAllPlugins` methods.
I think this should solve it, if not feel free to create a new issue.

**Comment by timdeschryver** [comment]
fyi, I've revisited the peer depedency of immer.
This library will include immer, but I've created [ngrx-immer](https://github.com/timdeschryver/ngrx-immer), in which immer is now a peer depedency.
