### ISSUE TITLE
Deprecation in favour of ngrx-immer

### ISSUE THREAD

**Issue by rainerhahnekamp** [timdeschryver/ngrx-etc#19]
I had some troubles with ngrx v11. `mutableOn` always defined the type of the state as unknown. A switch to ngrx-immer solved the problem at once.

What is the difference between these two libraries? If they serve the same purpose, wouldn't it be better to deprecate one?

**Comment by timdeschryver** [comment]
Hi, thanks for the report - I'll have to take a look at why this happens.
The idea behind this library is to add more functionality, but it never happened 😅
Revently, I extracted immer into ngrx-immer so consumers can pick their immer version.

**Comment by rainerhahnekamp** [comment]
Thanks for the answer. So I understand that it might be possible that ngrx-etc can get more features than ngrx-immer. Until that, both are "more or less" the same. 👍
