### ISSUE TITLE
Error: Angry over 'on' vs 'On'

### ISSUE THREAD

**Issue by Svenpire** [timdeschryver/ngrx-etc#21]
Hello, 
Thanks for this awesome library! But I'm getting the following issue on install at run time (angular 11): 
 `Error: node_modules/ngrx-immer/esm/store/index.d.ts:1:18 - error TS2724: '"../../../@ngrx/store/ngrx-store"' has no exported member named 'On'. Did you mean 'on'?`

Reference [Weilder Issue](https://gitmemory.com/issue/nilsmehlhorn/ngrx-wieder/33/804944479)
I'm unclear as to whether this means this will be updated for ngrx-etc or not. Is there a workaround in the mean time?

**Comment by timdeschryver** [comment]
Hi @Svenpire it's a bit unclear what you're trying to do.
Could you share a code snippet please?
Also, the versions of typescript, ngrx and ngrx-etc would be helpful.

**Comment by Svenpire** [comment]
Hi Tim, 
Thanks for getting back to me so quickly (great blog, by the way).

```
  "dependencies": {
    "@ngrx/store": "^11.1.1",
    "ngrx-etc": "^5.0.2",
  },
  "devDependencies": {
    "@ngrx/schematics": "^12.0.0",
    "typescript": "~4.1.5"
  }
```

I'll include the ngrx import in a reducer and do something like 
```
mutableOn(AuthActions.addContact, (state: State, action) => {
    return state.user.contacts.push({
      name: action.name,
      ...
  }
```

Then I get this fun message at run time
```
[1] Warning: C:\Users\svenp\Coding Projects\My Projects\salad-too\src\app\store\auth\auth.reducer.ts depends on 'ngrx-etc'. CommonJS or AMD dependencies can cause optimization bailouts.
[1] For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
[1]
[1]
[1]
[1] Error: node_modules/ngrx-immer/esm/store/index.d.ts:1:18 - error TS2724: '"../../../@ngrx/store/ngrx-store"' has no exported member named 'On'. Did you mean 'on'?
[1]
[1] 1 import { Action, On, ActionReducer, ActionCreator, ActionType } from '@ngrx/store';
```
Issue indicated at 'On'.

**Comment by timdeschryver** [comment]
Thanks for the info @Svenpire .
Could you try out v6.0.0 of ngrx-etc please (I've upgrade the angular and ngrx versions)?

**Comment by Svenpire** [comment]
Compiled successfully (and tested a small bit). 

Thanks!
