### ISSUE TITLE
Do we need to add a license file?

### ISSUE THREAD

**Issue by xianshenglu** [timdeschryver/ngrx-etc#22]
Hi, thanks for providing this great library. I am really enjoying this.

I just found that we have `"license": "MIT",` in the package.json while we didn't have the license file. So, do we need to add a license file?

**Comment by timdeschryver** [comment]
@xianshenglu feel free to create a LICENSE in this repository.
You can copy the one from [ngrx-immer](https://github.com/timdeschryver/ngrx-immer/blob/main/LICENSE).
