### ISSUE TITLE
@ngrx/data 8.5x breaking change

### ISSUE THREAD

**Issue by mickdelaney** [timdeschryver/ngrx-etc#9]
Looks like there's an issue when upgrading to @ngrx/data 8.5.2 

```
ERROR in ../../../node_modules/ngrx-etc/correlate/correlate-action.d.ts:2:23 - error TS2305: Module '"/node_modules/@ngrx/store/src/models"' has no exported member 'DisallowTypeProperty'.

2 import { TypedAction, **DisallowTypeProperty**, FunctionWithParametersType } from '@ngrx/store/src/models';
                        ~~~~~~~~~~~~~~~~~~~~

```

I've downgraded back to 8.4x for now. 
Let me know if i can help.

**Comment by timdeschryver** [comment]
Thanks for letting us know @mickdelaney, I will have a look later today.

**Comment by timdeschryver** [comment]
@mickdelaney I think this should fix the issue you experienced. If that's not the case feel free to re-open the issue.
